const mongoose = require("mongoose");
const { type } = require("../schema");
const Schema = mongoose.Schema;

// main()
// .catch(err => console.log(err));

// async function main() {
//   await mongoose.connect(process.env.ATLAS_DB);
// }

const dataSchema = new Schema({
        surveyorName:{
            type:String
        },
        respondentName:{
            type:String
        },
        villageTown:{
            type:String
        },
        occupation:{
            type:String,
            required:true
        },
        gender:{
            type:String,
            required:true
        },
        age:{
            type:Number,
            required:true
        },
        location:{
            type:String,
            required:true
        },
        qualification:{
            type:String,
            required:true
        },
        employment:{
            type:String,
            required:true
        },
        dailyWaterSource:{
            type:String,
            required:true
        },
        waterTreatment:{
            type:String,
            required:true
        },treatmentEntity:{
            type:String,
        },pipedWater:{
            type:String,
            required:true
        },waterShortages:{
            type:String,
            required:true
        },shortageSeason:{
            type:String,
        },
        dailyRiverUse:{
            type:String,
            required:true
        },riverLivelihood:{
            type:String,
            required:true
        },
        riverPayment:{
            type:String,
            required:true
        },paymentRecipient:{
            type:String,
        },
        riverDrinking:{
            type:String,
            required:true
        },
        drinkTreatment:{
            type:String,
        },
        domesticUse:{
            type:String,
            required:true
        },
        domesticPurpose:{
            type:String,
        },
        irrigation:{
            type:String,
            required:true
        },
        cropImpact:{
            type:String,
        },
        waterQualityChange:{
            type:String,
            required:true
        },
        qualityChangeDescription:{
            type:String,
        },
        seasonalChange:{
            type:String,
            required:true
        },
        seasonDescription:{
            type:String,
        },
        waterborneDisease:{
            type:String,
            required:true
        },
        diseaseTypes:{
            type:String,
        },
        deadFishObservation:{
            type:String,
            required:true
        },
        fishSeason:{
            type:String,
        },
        wastewaterStream:{
            type:String,
            required:true
        },
        streamLocations:{
            type:String,
        },
        industryWasteEvidence:{
            type:String,
            required:true
        },
        industryWasteLocations:{
            type:String,
        },

        fishDecline:{
            type:String,
            required:true
        },
        declinedSpecies:{
            type:String,
        },
        animalDecline:{
            type:String,
            required:true
        },
        declinedBirdsAnimals:{
            type:String,
        },
        illegalActivities:{
            type:String,
            required:true
        },
        illegalImpact:{
            type:String,
        },
        regularSpecies:{
            type:String,
            required:true
        },
        disappearedSpecies:{
            type:String,
            required:true
        },
        livelihoodOptions:{
            type:Array,
            required:true
        },
        otherLivelihoodDetail:{
            type:String,
        },
        fishingImportance:{
            type:String,
            required:true
        },
        catchDecrease:{
            type:String,
        },
        earningsImpact:{
            type:String,
            required:true
        },
        businessImpact:{
            type:String,
            required:true
        },
        localMyths:{
            type:String,
            required:true
        },
        festivalsEvents:{
            type:String,
            required:true
        },
        traditionChanges:{
            type:String,
            required:true
        },
        traditionChangesDetail:{
            type:String,
        },
        sacredSites:{
            type:String,
            required:true
        },
        sacredSitesDetail:{
            type:String,
        },
        culturalImportance:{
            type:String,
            required:true
        }
        ,
        wastewaterDisposal:{
            type:Array,
            required:true
        },
        drainageSystem:{
            type:String,
            required:true
        },
        maintenance:{
            type:String,
        },
        stpsAvailable:{
            type:String,
            required:true
        },
        stpsFunctional:{
            type:String,
        },
        industryWasteTreatment:{
            type:String,
            required:true
        },
        treatmentMethods:{
            type:String,
        },
        sewageDischarge:{
            type:String,
            required:true
        },
        dischargeLocations:{
            type:String,
        },
        householdWaste:{
            type:Array,
            required:true
        },
        garbageCollection:{
            type:String,
            required:true
        },
        regularClearing:{
            type:String,
        },
        wasteSegregation:{
            type:String,
            required:true
        },
        categories:{
            type:String,
        },
        plasticWaste:{
            type:String,
            required:true
        },
        sources:{
            type:String,
        },
        marketWaste:{
            type:String,
            required:true
        },
        wasteType:{
            type:String,
        },
        wasteFacility:{
            type:String,
            required:true
        },
        facilityFunctional:{
            type:String,
        },
        awareness:{
            type:String,
            required:true
        },
        campaignDetails:{
            type:String,
        },
        illegalDumping:{
            type:String,
            required:true
        },
        dumpingLocations:{
            type:String,
        },
        wasteCollectionStatus:{
            type:String,
            required:true
        },
        riverChallenges:{
            type:String,
            required:true
        },
        improvementActions:{
            type:String,
            required:true
        },
        pollutionSources:{
            type:String,
            required:true
        },
        govProgramsAwareness:{
            type:String,
            required:true
        },
        localInitiatives:{
            type:String,
            required:true
        },
        willingnessParticipation:{
            type:String,
            required:true
        },
        photographsCompleted:{
            type:String,
            required:true
        },
        photographsRemarks:{
            type:String,
        },
        videoInterviewsCompleted:{
            type:String,
            required:true
        },
        videoInterviewsRemarks:{
            type:String,
        },
        contactName:{
            type:String,
        },
        contactPhone:{
            type:String,
        },
        regularUpdates:{
            type:String,
        },
        date:{
            type:Date,
            default:Date().now
        },
        user:{
            type:Schema.Types.ObjectId,
            ref:"User"
        }
   
})

const Data =  mongoose.model("Data",dataSchema);

module.exports=Data;